# Generated by Django 5.1.7 on 2025-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_conta',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('comprador', 'Comprador')], default='comprador', max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, default='Sem endereço informado', null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True, default='Sem endereço informado', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='Sem endereço informado', max_length=15),
            preserve_default=False,
        ),
    ]
