# Generated by Django 5.1.7 on 2025-08-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_produto_imagem_avaliacao_listadesejos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
